model: loanApplication

initialScreen: enterMemberIdNo

enterMemberIdNo:
  order: 0
  type: inputScreen
  text:
    en: Member ID Number
    ny: Nambala Yamembala
  inputIdentifier: memberIdNumber
  nextScreen: enterEmploymentNumber

enterEmploymentNumber:
  order: 1
  type: inputScreen
  text:
    en: Employment Number
    ny: Nambala Yakuntchito
  inputIdentifier: employeeNumber
  nextScreen: enterLoanType

enterLoanType:
  order: 2
  type: inputScreen
  text:
    en: Loan Type
    ny: Mtundu Wangongole
  options:
    - position: 1
      label:
        en: Personal
        ny: Yamunthu
      code: PERSONAL
    - position: 2
      label:
        en: Business
        ny: Bizinesi
      code: BUSINESS
    - position: 3
      label:
        en: Agricultural
        ny: Yaulimi
      code: AGRICULTURAL
    - position: 4
      label:
        en: Emergency
        ny: Yapangozi
      code: EMERGENCY
  inputIdentifier: loanType
  nextScreen: enterLoanAmount

enterLoanAmount:
  order: 3
  type: inputScreen
  text:
    en: Loan Amount
    ny: Kuchuluka Kwake
  inputIdentifier: loanAmount
  nextScreen: enterPurposeOfLoan

enterPurposeOfLoan:
  order: 4
  type: inputScreen
  text:
    en: Loan Purpose
    ny: Cholinga Changongole
  inputIdentifier: loanPurpose
  nextScreen: enterRepaymentPeriod

enterRepaymentPeriod:
  order: 5
  type: inputScreen
  text:
    en: Repayment Months
    ny: Miyezi Yobweza
  inputIdentifier: repaymentPeriod
  nextScreen:
