enterDescription:
  inputIdentifier: description
  nextScreen: enterValue
  order: 1
  text:
    en: Description
  type: inputScreen
enterId:
  hidden: true
  inputIdentifier: id
  type: hiddenField
enterMemberId:
  hidden: true
  inputIdentifier: memberId
  type: hiddenField
enterMemberLoanId:
  hidden: true
  inputIdentifier: memberLoanId
  type: hiddenField
enterSerialNumber:
  inputIdentifier: serialNumber
  nextScreen: formSummary
  optional: true
  order: 3
  text:
    en: Serial Number
  type: inputScreen
enterValue:
  inputIdentifier: value
  nextScreen: enterSerialNumber
  order: 2
  text:
    en: Value
  type: inputScreen
  validationRule: ^\d+\.*\d*$
formSummary:
  type: quitScreen
initialScreen: enterDescription
model: memberLoanSecurity
